<?php require APPROOT . '/views/components/header.php'; ?>
<link rel="stylesheet" href="<?php echo URLROOT; ?>/css/pages/admin/reports.css">
<div class="main-container">
    <?php require APPROOT . '/views/components/adminSidePanel.php'; ?>
    <main class="content-area">
        <div class="report-header">
            <button class="back-btn" onclick="window.location.href='<?php echo URLROOT; ?>/admin/reports'">
                <span class="material-symbols-outlined">arrow_back_ios</span>
                <h1>Reports</h1>
            </button>
            <div class="report-actions">

                <a href="<?= URLROOT ?>/admin/downloadReport/<?= $data['reportSlug'] ?>?timePeriod=<?= $data['timePeriod'] ?>&startDate=<?= $data['startDate'] ?>&endDate=<?= $data['endDate'] ?>">
                    <i class="fas fa-download"></i> Download CSV
                </a>
                <a href="<?= URLROOT ?>/admin/downloadPdf/<?= $data['reportSlug'] ?>?timePeriod=<?= $data['timePeriod'] ?>&startDate=<?= $data['startDate'] ?>&endDate=<?= $data['endDate'] ?>">
                    <i class="fas fa-download"></i> Download PDF
                </a>
            </div>
        </div>

        <div class="report-content">
            <div class="print-only-title">
                <h1><?= $data['reportName'] ?> Report</h1>
                <p>Generated on <?= date('F j, Y') ?></p>
            </div>

            <div class="report-summary">
                <div class="summary-card">
                    <h3>Total Records</h3>
                    <p><?= count($data['reportData']) ?></p>
                </div>
                
                <div class="time-period-filter" style="<?php echo ($data['reportSlug'] == 'SystemHealth' || $data['reportSlug'] == 'ExecutiveSummary') ? 'display: none;' : '' ?>">
                    <form id="timeFilterForm" class = "timeFilterForm" method="get">
                        <select name="timePeriod" id="timePeriod" onchange="updateTimeFilter()">
                            <option value="all" <?= $data['timePeriod'] === 'all' ? 'selected' : '' ?>>All Time</option>
                            <option value="1month" <?= $data['timePeriod'] === '1month' ? 'selected' : '' ?>>Last 1 Month</option>
                            <option value="3months" <?= $data['timePeriod'] === '3months' ? 'selected' : '' ?>>Last 3 Months</option>
                            <option value="6months" <?= $data['timePeriod'] === '6months' ? 'selected' : '' ?>>Last 6 Months</option>
                            <option value="1year" <?= $data['timePeriod'] === '1year' ? 'selected' : '' ?>>Last 1 Year</option>
                            <option value="custom" <?= $data['timePeriod'] === 'custom' ? 'selected' : '' ?>>Custom Range</option>
                        </select>

                        <div id="customDateRange" style="display: <?= $data['timePeriod'] === 'custom' ? 'flex' : 'none' ?>;">
                            <input type="date" name="startDate" value="<?= $data['startDate'] ?>">
                            <span>to</span>
                            <input type="date" name="endDate" value="<?= $data['endDate'] ?>">
                        </div>

                        <button type="submit">Apply</button>
                    </form>
                </div>
            </div>

            <div class="report-table-container">
                <table class="report-table">
                    <thead>
                        <tr>
                            <?php if (!empty($data['reportData'])): ?>
                                <?php foreach (array_keys((array)$data['reportData'][0]) as $column): ?>
                                    <th><?= ucwords(str_replace('_', ' ', $column)) ?></th>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data['reportData'] as $row): ?>
                            <tr>
                                <?php foreach ((array)$row as $value): ?>
                                    <td><?= htmlspecialchars($value ?? 'N/A') ?></td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="print-footer">
                Report generated by UniQuest Admin Dashboard
            </div>
        </div>
    </main>
</div>

<?php require APPROOT . '/views/components/footer.php'; ?>
<script>
function updateTimeFilter() {
    const timePeriod = document.getElementById('timePeriod').value;
    const customRange = document.getElementById('customDateRange');
    
    if (timePeriod === 'custom') {
        customRange.style.display = 'flex';
    } else {
        customRange.style.display = 'none';
    }
}
</script>