<?php require APPROOT . '/views/components/header.php'; ?>
<link rel="stylesheet" href="<?php echo URLROOT; ?>/css/pages/admin/reports.css">

<!-- Sidebar and Content Layout -->
<div class="main-container">
    <!-- Sidebar -->
    <?php require APPROOT . '/views/components/adminSidePanel.php'; ?>

    <!-- Content Area -->
    <main class="content-area">
        <div class="report-header">
            <h1><?= $data['reportName'] ?> Report</h1>
            <div class="report-actions">
                <a href="<?= URLROOT ?>/admin/reports" class="btn btn-secondary">
                    <i class="fas fa-arrow-left"></i> Back to Reports
                </a>
                <a href="<?= URLROOT ?>/admin/downloadReport/<?= $data['reportSlug'] ?>" class="btn btn-primary">
                    <i class="fas fa-download"></i> Download CSV
                </a>
                <a href="<?= URLROOT ?>/admin/downloadPdf/<?= $data['reportSlug'] ?>" class="btn btn-primary">
                    <i class="fas fa-download"></i> Download PDF
                </a>
                <button onclick="generatePDF()" class="btn btn-danger">
                    <i class="fas fa-file-pdf"></i> Save as PDF
                </button>
            </div>
        </div>

        <div class="report-content">
            <div class="print-only-title">
                <h1><?= $data['reportName'] ?> Report</h1>
                <p>Generated on <?= date('F j, Y') ?></p>
            </div>

            <div class="report-summary">
                <div class="summary-card">
                    <h3>Total Records</h3>
                    <p><?= count($data['reportData']) ?></p>
                </div>
                <!-- Add more summary cards as needed -->
            </div>

            <div class="report-table-container">
                <table class="report-table">
                    <thead>
                        <tr>
                            <?php if (!empty($data['reportData'])): ?>
                                <?php foreach (array_keys((array)$data['reportData'][0]) as $column): ?>
                                    <th><?= ucwords(str_replace('_', ' ', $column)) ?></th>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($data['reportData'] as $row): ?>
                            <tr>
                                <?php foreach ((array)$row as $value): ?>
                                    <td><?= htmlspecialchars($value) ?></td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="print-footer">
                Report generated by UniQuest Admin Dashboard
            </div>
        </div>
    </main>
</div>

<!-- Footer -->
<?php require APPROOT . '/views/components/footer.php'; ?>

<script>
    function generatePDF() {
        // Store original styles
        const originalStyles = {};
        const styleElements = document.querySelectorAll('style, link[rel="stylesheet"]');

        // Create print-specific styles
        const printStyle = document.createElement('style');
        printStyle.innerHTML = `
        @media print {
            body * { visibility: hidden; }
            .content-area, .content-area * { visibility: visible; }
            .content-area { 
                position: absolute; 
                left: 0; 
                top: 0; 
                width: 100%; 
                padding: 0; 
                margin: 0; 
            }
            .report-actions, .report-summary { display: none !important; }
        }
    `;
        document.head.appendChild(printStyle);

        // Temporarily hide elements
        const elementsToHide = document.querySelectorAll('header, footer, .main-container > :not(.content-area)');
        elementsToHide.forEach(el => {
            originalStyles[el.id || el.className] = el.style.cssText;
            el.style.display = 'none';
        });

        // Print
        window.print();

        // Restore original state
        setTimeout(() => {
            elementsToHide.forEach(el => {
                el.style.cssText = originalStyles[el.id || el.className];
            });
            printStyle.remove();
        }, 500);
    }
</script>